#!/bin/bash

# Generate your Dropbox token: https://www.dropbox.com/developers/apps
DROPBOX_TOKEN=Gx1iJ8k2v6kAAAAAAAAAWQbplCmha_zdjlJcSXGIaF4tSbFmn4yvWqTTcTFF6zpA

# Database connection data
MYSQL_PASSWORD_FILE="/var/lib/mysql/autogenerated"
MYSQL_WORDPRESS_USER="wordpress";
MYSQL_WORDPRESS_DATABASE="wordpress";
MYSQL_RANDOM_ROOT_PASSWORD=`head -1 ${MYSQL_PASSWORD_FILE}`;
MYSQL_WORDPRESS_USER_PASSWORD=`tail -1 ${MYSQL_PASSWORD_FILE}`;

# If you have multiple folders with WordPress files, add/remove them from this array
directories=( "/var/www/wp-content" )

for searchFolder in "${directories[@]}"
do
  echo -e "Backing up ${searchFolder} \n"
  cd $searchFolder

  echo -e "Compressing directory... ${searchFolder}\n"
  BACKUP_FILENAME=wordpress_backup_$(basename "${searchFolder}")_$(date +"%y-%m-%d_%H:%M:%S").tar.gz
  tar czf /tmp/${BACKUP_FILENAME} ${searchFolder}

  echo -e "Uploading to Dropbox...\n"
  curl -k --progress-bar -i --globoff -o /tmp/dropbox_${BACKUP_FILENAME} --upload-file /tmp/${BACKUP_FILENAME} https://api-content.dropbox.com/1/files_put/auto/${BACKUP_FILENAME}  -H "Authorization:Bearer $DROPBOX_TOKEN"

  echo -e "Removing files...\n"
  rm /tmp/${BACKUP_FILENAME}
done
  
echo -e "Exporting database...\n"
DATABASE_FILENAME=backpup_database_$(date +"%y-%m-%d_%H:%M:%S").tar.gz.sql
mysqldump -u${MYSQL_WORDPRESS_USER} -p${MYSQL_WORDPRESS_USER_PASSWORD} ${MYSQL_WORDPRESS_DATABASE} | gzip -v > /tmp/${DATABASE_FILENAME}

echo -e "Uploading database to Dropbox...\n"
curl -k --progress-bar -i --globoff -o /tmp/dropbox_${DATABASE_FILENAME} --upload-file /tmp/${DATABASE_FILENAME} https://api-content.dropbox.com/1/files_put/auto/${DATABASE_FILENAME}  -H "Authorization:Bearer $DROPBOX_TOKEN"

echo -e "Removing database file...\n"
rm /tmp/${DATABASE_FILENAME}

echo -e "Done\n"